services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: dog123
      MYSQL_DATABASE: dog
      MYSQL_USER: dog
      MYSQL_PASSWORD: dog123
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data:
